### ISSUE TITLE
ERROR: Permission denied for user: 'None'. [Remote: conan-community]

### ISSUE THREAD

**Issue by CeccAnd** [SolarFramework/SolARFramework#47]
Hello

after remaken install packagedependencies.txt, I obtained following errors:

WARN: libtiff/4.2.0: requirement zlib/1.2.11 overridden by opencv/4.4.0@conan-solar/stable to zlib/1.2.11@conan-solar/stable
WARN: libtiff/4.2.0: requirement libjpeg/9d overridden by opencv/4.4.0@conan-solar/stable to libjpeg/9d@conan-solar/stable
WARN: libtiff/4.2.0: requirement libwebp/1.2.0 overridden by opencv/4.4.0@conan-solar/stable to libwebp/1.0.3@conan-solar/stable
xz_utils/5.2.5: Not found in local cache, looking in remotes...
xz_utils/5.2.5: Trying with 'conan-solar'...
xz_utils/5.2.5: Trying with 'conan-community'...
ERROR: Failed requirement 'xz_utils/5.2.5' from 'libtiff/4.2.0'
ERROR: Permission denied for user: 'None'. [Remote: conan-community]
[2021-09-01 17:33:44.359743] [0x00001068] [error]   Unable to find 'opencv:4.4.0' on conan('conan-solar')
[2021-09-01 17:33:44.361748] [0x00001068] [error]   Error installing conan dependency : opencv/4.4.0@conan-solar/stable

**Comment by jim-bcom** [comment]
Hello,

You seem to have 'conan-community' remote at index 1 of your conan remote list.
This remote is now deprecated (source: https://docs.conan.io/en/1.32/uploading_packages/remotes.html#conan-community) which may explain the error.

We recommend the following remote list to be configured:

```
>conan remote list
conan-solar: https://artifact.b-com.com/api/conan/solar-conan-local [Verify SSL: True]
conan-bcom: https://artifact.b-com.com/api/conan/bcom-conan-local [Verify SSL: True]
conancenter: https://center.conan.io [Verify SSL: True]
conan-center: https://conan.bintray.com [Verify SSL: True]
bincrafters: https://bincrafters.jfrog.io/artifactory/api/conan/public-conan [Verify SSL: True]
```

Let us know if this solves your problem.

Thanks for trying SoLAR.

**Comment by jim-bcom** [comment]
Closing this issue because it has not had recent activity.

**Comment by jim-bcom** [comment]
Closing this issue because it has not had recent activity.
